Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clinica/', include("clinica.urls"))
]

clinica/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),

    path("pacientescargar", views.pacientescargar, name="pacientescargar"),
    path("pacientesindex", views.pacientesindex, name="pacientesindex"),
    path("pacienteshow/<int:paciente_id>", views.pacienteshow, name="pacienteshow"),
    path("pacientesupdate/<int:paciente_id>", views.pacientesupdate, name="pacientesupdate"),
    path("pacientesdelete/<int:paciente_id>", views.pacientesdelete, name="pacientesdelete"),

    path("historialshow/<int:historial_id>", views.historialshow, name="historialshow"),
    path("historialupdate/<int:historial_id>", views.historialupdate, name="historialupdate"),
    path("historialdelete/<int:historial_id>", views.historialdelete, name="historialdelete"),

    path("turnoscreate", views.turnoscreate, name="turnoscreate"),
    path("turnosindex", views.turnosindex, name="turnosindex"),
    path("turnoshow/<int:turno_id>", views.turnoshow, name="turnoshow"),
    path("turnosupdate/<int:turno_id>", views.turnosupdate, name="turnosupdate"),
    path("turnosdelete/<int:turno_id>", views.turnosdelete, name="turnosdelete"),
    path("turnoasistencia/<int:turno_id><int:asistencia_id>", views.turnoasistencia, name="turnoasistencia"),

    path("categoriascreate", views.categoriascreate, name="categoriascreate"),
    path("categoriasindex", views.categoriasindex, name="categoriasindex"),
    path("categoriashow/<int:categoria_id>", views.categoriashow, name="categoriashow"),
    path("categoriasupdate/<int:categoria_id>", views.categoriasupdate, name="categoriasupdate"),
    path("categoriasdelete/<int:categoria_id>", views.categoriasdelete, name="categoriasdelete"),

    path("productoscreate", views.productoscreate, name="productoscreate"),
    path("productosindex", views.productosindex, name="productosindex"),
    path("productoshow/<int:producto_id>", views.productoshow, name="productoshow"),
    path("productosupdate/<int:producto_id>", views.productosupdate, name="productosupdate"),
    path("productosdelete/<int:producto_id>", views.productosdelete, name="productosdelete"),

    path("pedidoscreate", views.pedidoscreate, name="pedidoscreate"),
    path("pedidosindex", views.pedidosindex, name="pedidosindex"),
    path("pedidoshow/<int:pedido_id>", views.pedidoshow, name="pedidoshow"),
    path("pedidosupdate/<int:pedido_id>", views.pedidosupdate, name="pedidosupdate"),
    path("pedidosdelete/<int:pedido_id>", views.pedidosdelete, name="pedidosdelete"),
    path("pedidoestado/<int:pedido_id><int:estado_id>", views.pedidoestado, name="pedidoestado"),

    path("consulta", views.consulta, name="consulta"),

    path("itemdelete/<int:item_id>", views.itemdelete, name="itemdelete"),

    path("reportepacientes/<int:asistencia_id><int:rango>", views.reportepacientes, name="reportepacientes"),
    path("reportepacientespedidos/<int:rango>", views.reportepacientespedidos, name="reportepacientespedidos"),
    path("reporteproductos", views.reporteproductos, name="reporteproductos"),
    path("reporteventas", views.reporteventas, name="reporteventas"),
]

clinica/models.py
from django.conf import settings
from django.db import models

# Create your models here.

class Paciente(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    nombre = models.CharField(max_length=64)
    apellido = models.CharField(max_length=64)
    dni = models.IntegerField()
    telefono = models.CharField(max_length=64)
    direccion = models.CharField(max_length=64)
    email = models.CharField(max_length=64)
    # Método para mostrar el atributo nombre en la lista desplegable
    def __str__(self):
        return u'{0}'.format(self.nombre)

class Asistencia(models.Model):
    nombre = models.CharField(max_length=64)
    def __str__(self):
        return u'{0}'.format(self.nombre)

class Turno(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    asistencia = models.ForeignKey(Asistencia, on_delete=models.CASCADE)
    fecha = models.DateField()
    hora = models.TimeField()


class Categoria(models.Model):
    nombre = models.CharField(max_length=64)
    def __str__(self):
        return u'{0}'.format(self.nombre)

class Producto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=64)
    precio = models.IntegerField()
    detalle = models.CharField(max_length=64)
    def __str__(self):
        return u'{0}'.format(self.nombre)

class Estado(models.Model):
    nombre = models.CharField(max_length=64)
    def __str__(self):
        return u'{0}'.format(self.nombre)

class Tipopago(models.Model):
    nombre = models.CharField(max_length=64)
    def __str__(self):
        return u'{0}'.format(self.nombre)

class Pedido(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    tipopago = models.ForeignKey(Tipopago, on_delete=models.CASCADE)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)
    total = models.IntegerField()
    fechaentrega = models.DateField()

class Distancia(models.Model):
    nombre = models.CharField(max_length=64)
    def __str__(self):
        return u'{0}'.format(self.nombre)

class Lado(models.Model):
    nombre = models.CharField(max_length=64)
    def __str__(self):
        return u'{0}'.format(self.nombre)

class Armazon(models.Model):
    nombre = models.CharField(max_length=64)
    def __str__(self):
        return u'{0}'.format(self.nombre)

class Subpedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    distancia = models.ForeignKey(Distancia, on_delete=models.CASCADE)
    lado = models.ForeignKey(Lado, on_delete=models.CASCADE)
    armazon = models.ForeignKey(Armazon, on_delete=models.CASCADE)
    cantidad = models.IntegerField()

class Historial(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    titulo = models.CharField(max_length=64)
    detalle = models.TextField()

clinica/views.py
from django.shortcuts import render, redirect
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from .models import Paciente, Turno, Categoria, Producto, Tipopago, Estado, Pedido, Subpedido, Distancia, Armazon, Lado, Historial
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group, User
from django.contrib import messages
import xlsxwriter
import io
from datetime import date, timedelta

# Create your views here.

# Views para Pacientes
class FormPaciente(forms.Form):
    nombre = forms.CharField(label="Nombre:", widget=forms.TextInput(attrs={'class':'form-control'}))
    apellido = forms.CharField(label="Apellido:", widget=forms.TextInput(attrs={'class':'form-control'}))
    dni = forms.IntegerField(label="DNI:", widget=forms.TextInput(attrs={'class':'form-control'}))
    telefono = forms.CharField(label="Teléfono:", widget=forms.TextInput(attrs={'class':'form-control'}))
    direccion = forms.CharField(label="Dirección:", widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.CharField(label="E-Mail", widget=forms.TextInput(attrs={'class':'form-control'}))

class FormHistorial(forms.Form):
    titulo = forms.CharField(label="Título:", widget=forms.TextInput(attrs={'class':'form-control'}))
    detalle = forms.CharField(label="Detalle:", widget=forms.Textarea(attrs={'class':'form-control'}))

def pacientescargar(request):
    # Rechazamos acceso y derivamos a la pantalla de login si no hay un usuario autenticado
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))

    if request.method == "POST":
        form = FormPaciente(request.POST)
        if form.is_valid():
            nombre = form.cleaned_data["nombre"]
            apellido = form.cleaned_data["apellido"]
            dni = form.cleaned_data["dni"]
            telefono = form.cleaned_data["telefono"]
            direccion = form.cleaned_data["direccion"]
            email = form.cleaned_data["email"]
            p = Paciente(nombre=nombre, apellido=apellido, dni=dni, telefono=telefono, direccion=direccion, email=email, user_id=2)
            messages.success(request, 'El Paciente fue Cargado Exitosamente')
            p.save()
        return HttpResponseRedirect(reverse("pacientesindex"))
    else:
        return render(request, "pacientes/form.html", {
            "form" : FormPaciente()
        })

def pacientesindex(request):
    # Rechazamos acceso y derivamos a la pantalla de login si no hay un usuario autenticado
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))

    pacientes = Paciente.objects.all()
    return render(request, "pacientes/index.html", {
        "pacientes" : pacientes
    })

def pacientesupdate(request, paciente_id):
     # Rechazamos acceso y derivamos a la pantalla de login si no hay un usuario autenticado
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))

    paciente = Paciente.objects.get(id=paciente_id)
    form = FormPaciente(request.POST)
    if form.is_valid():
        paciente.nombre = form.cleaned_data["nombre"]
        paciente.apellido = form.cleaned_data["apellido"]
        paciente.dni = form.cleaned_data["dni"]
        paciente.telefono = form.cleaned_data["telefono"]
        paciente.direccion = form.cleaned_data["direccion"]
        paciente.email = form.cleaned_data["email"]
        paciente.save()
        messages.success(request, 'El Paciente fue Modificado Exitosamente')
        return HttpResponseRedirect(reverse("pacientesindex"))
    return render(request, 'pacientes/update.html', {
        'id': paciente.id,
        'form': FormPaciente(initial={'id': paciente.id, 'nombre': paciente.nombre, 'apellido': paciente.apellido, 'dni': paciente.dni, 'telefono': paciente.telefono, 'direccion': paciente.direccion,'email': paciente.email})
    })

def pacientesdelete(request, paciente_id):
     # Rechazamos acceso y derivamos a la pantalla de login si no hay un usuario autenticado
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))

    Paciente.objects.get(id=paciente_id).delete()
    messages.success(request, 'El Paciente fue Eliminado Exitosamente')
    return HttpResponseRedirect(reverse("pacientesindex"))

def pacienteshow(request, paciente_id):
     # Rechazamos acceso y derivamos a la pantalla de login si no hay un usuario autenticado
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))

    paciente = Paciente.objects.get(id=paciente_id)
    historiales = Historial.objects.filter(paciente_id=paciente_id)
    if request.method == "POST":
        form = FormHistorial(request.POST)
        if form.is_valid():
            titulo = form.cleaned_data["titulo"]
            detalle = form.cleaned_data["detalle"]
            p = Historial(paciente_id=paciente_id, user_id=request.user.id, titulo=titulo, detalle=detalle)
            p.save()
            messages.success(request, 'El Registro fue Agregado Exitosamente')
            return redirect('pacienteshow', paciente_id)
    else:
        return render(request, "pacientes/show.html", {
            "paciente": paciente,
            "historiales": historiales,
            "form" : FormHistorial()
        })

# Views para Historiales
def historialupdate(request, historial_id):
     # Rechazamos acceso y derivamos a la pantalla de login si no hay un usuario autenticado
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))

    historial = Historial.objects.get(id=historial_id)
    form = FormHistorial(request.POST)
    if form.is_valid():
        historial.titulo = form.cleaned_data["titulo"]
        historial.detalle = form.cleaned_data["detalle"]
        historial.save()
        messages.success(request, 'El Registro fue modificado Exitosamente')
        return redirect('pacienteshow', historial.paciente_id)
    return render(request, 'historiales/update.html', {
        'id': historial.id,
        'paciente_id': historial.paciente_id,
        'form': FormHistorial(initial={'id': historial.id, 'titulo': historial.titulo, 'detalle': historial.detalle})
    })

def historialdelete(request, historial_id):
     # Rechazamos acceso y derivamos a la pantalla de login si no hay un usuario autenticado
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))

    historial = Historial.objects.get(id=historial_id)
    paciente_id = historial.paciente_id
    historial.delete()
    messages.success(request, 'El Registro fue Eliminado Exitosamente')
    return redirect('pacienteshow', paciente_id)

def historialshow(request, historial_id):
     # Rechazamos acceso y derivamos a la pantalla de login si no hay un usuario autenticado
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))

    historial = Historial.objects.get(id=historial_id)
    return render(request, "historiales/show.html", {
        "historial": historial
    })

# Views para Turnos
class FormTurno(forms.Form):
    paciente = forms.ModelChoiceField(queryset=Paciente.objects.all(), required=True, widget=forms.Select(attrs={'class':'form-control'}))
    usuario = forms.ModelChoiceField(queryset=User.objects.filter(groups__name='Profesional Médico'), required=True, label="Profesional Médico:", widget=forms.Select(attrs={'class':'form-control'}))
    fecha = forms.DateField(label="Fecha:", widget=forms.DateInput(attrs={'class':'form-control','type':'date'}))
    hora = forms.TimeField(label="Hora:", widget=forms.TimeInput(attrs={'class':'form-control','type':'time'}))

def turnoscreate(request):
    # Rechazamos acceso y derivamos a la pantalla de login si no hay un usuario autenticado
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))

    if request.method == "POST":
        form = FormTurno(request.POST)
        #breakpoint()
        if form.is_valid():
            paciente = form.cleaned_data["paciente"].id
            fecha = form.cleaned_data["fecha"]
            hora = form.cleaned_data["hora"]
            usuario = form.cleaned_data["usuario"].id
            p = Turno(paciente_id=paciente, fecha=fecha, hora=hora, user_id=usuario, asistencia_id=1)
            messages.success(request, 'El Turno fue Creado Exitosamente')
            p.save()
        return HttpResponseRedirect(reverse("turnosindex"))
    else:
        return render(request, "turnos/create.html", {
            "form" : FormTurno()
        })

def turnosupdate(request, turno_id):
     # Rechazamos acceso y derivamos a la pantalla de login si no hay un usuario autenticado
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))

    turno = Turno.objects.get(id=turno_id)
    form = FormTurno(request.POST)
    if form.is_valid():
        turno.paciente_id = form.cleaned_data["paciente"].id
        turno.fecha = form.cleaned_data["fecha"]
        turno.hora = form.cleaned_data["hora"]
        turno.user_id = form.cleaned_data["usuario"].id
        turno.save()
        messages.success(request, 'El Turno fue Modificado Exitosamente')
        return HttpResponseRedirect(reverse("turnosindex"))
    return render(request, 'turnos/update.html', {
        'id': turno.id,
        'form': FormTurno(initial={'id': turno.id, 'paciente': turno.paciente_id, 'usuario': turno.user_id, 'fecha': turno.fecha, 'hora': turno.hora})
    })

def turnosdelete(request, turno_id):
     # Rechazamos acceso y derivamos a la pantalla de login si no hay un usuario autenticado
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))

    Turno.objects.get(id=turno_id).delete()
    messages.success(request, 'El Turno fue Eliminado Exitosamente')

clinica/templates/pedidos/create.html
{% extends "layout.html" %}
{% block body %}
    <div class="container">
        <div class="formulario">
            <h1>Nuevo Pedido:</h1>
            <form action="{% url 'pedidoscreate' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <div class="form-group" style="margin-top: 1rem;">
                    <input type="submit", class="btn btn-primary">
                    <a href="{% url 'pedidosindex' %}" class="btn btn-secondary">Volver</a>
                </div>
            </form>   
        </div>
    </div>
{% endblock %}

clinica/templates/pedidos/index.html
{% extends "layout.html" %}

{% block body %}
    <div class="container">

        {% if messages %}
            <div class="alert alert-primary" role="alert" style="text-align: center;">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}

        <h1>Pedidos</h1>
 
        <table class="table table-sm table-striped table-borderless">
            <thead class="table-dark">
                <tr>
                    <th>N°</th>
                    <th>Fecha de Entrega</th>
                    <th>Vendedor</th>
                    <th>Paciente</th>
                    <th>Estado</th>
                    {% if request.session.tipousuario_id != 4 %} <!-- Tipo de Usuarios Taller no visualizan los precios -->
                        <th>Total</th>
                    {% endif %}
                    <th>Tipo de Pago</th>
                    <th></th>
                </tr>
            </thead>
        
            <tbody>
                {% for pedido in pedidos %}
                    <tr>
                        <td>{{ pedido.id }}</td>
                        <td>{{ pedido.fechaentrega }}</td>
                        <td>{{ pedido.user.get_username }}</td>
                        <td>{{ pedido.paciente.nombre }}</td>
                        <td>{{ pedido.estado.nombre }}</td>
                        {% if request.session.tipousuario_id != 4 %} <!-- Tipo de Usuarios Taller no visualizan los precios -->
                            <td>{{ pedido.total }}$</td>
                        {% endif %}
                        <td>{{ pedido.tipopago.nombre }}</td>
                        <td style="width: 20%;">
                            <a href="{% url 'pedidoshow' pedido.id %}" class="btn btn-primary btn-sm botones-index">Detalle</a>
                            {% if request.session.tipousuario_id != 4 %} <!-- Tipo de Usuarios Taller no visualizan los precios -->
                                <a href="{% url 'pedidosdelete' pedido.id %}" class="btn btn-danger btn-sm botones-index">Eliminar</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if request.session.tipousuario_id != 4 %} <!-- Tipo de Usuarios Taller no puede generar pedidos -->
            <a href="{% url 'pedidoscreate' %}" class="btn btn-primary">Nuevo Pedido</a>
        {% endif %}
    </div>
    
{% endblock %}

clinica/templates/pedidos/show.html
{% extends "layout.html" %}

{% block body %}
    <div class="container">

        {% if messages %}
            <div class="alert alert-primary" role="alert" style="text-align: center;">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
        
        <div class="muestra" style="margin-bottom: 1rem;">
            <h2>Detalle del Pedido</h2>
            <ul>
                <li><strong>N°:</strong> {{pedido.id }}</li>
                <li><strong>Fecha de Entrega:</strong> {{ pedido.fechaentrega }}</li>
                <li><strong>Vendedor:</strong> {{ pedido.user.get_username }}</li>
                <li><strong>Paciente:</strong> {{ pedido.paciente.nombre }}</li>
                <li><strong>Estado:</strong> {{ pedido.estado.nombre }}</li>
                {% if request.session.tipousuario_id != 4 %} <!-- Tipo de Usuarios Taller no visualizan los precios -->
                    <li><strong>Total:</strong> {{ pedido.total }}$</li>
                {% endif %}
                <li><strong>Tipo de Pago:</strong> {{ pedido.tipopago.nombre }}</li>
                <li><strong>Creado:</strong> {{ pedido.created_at }}</li>
            </ul>

            <a href="{% url 'pedidosindex' %}" class="btn btn-secondary">Volver</a>

            {% if request.session.tipousuario_id == 3 or request.session.tipousuario_id == 5 %} <!-- Tipo de Usuarios Ventas y Gerencia-->
                <a href="{% url 'pedidosupdate' pedido.id %}" class="btn btn-primary">Modificar Datos del Pedido</a>
                <a href="{% url 'pedidoestado' pedido.id 2 %}" class="btn btn-success">Cambiar Estado a Pedido</a>
                <a href="{% url 'pedidoestado' pedido.id 3 %}" class="btn btn-success">Cambiar Estado a Taller</a>
            {% endif %}

            {% if request.session.tipousuario_id == 4 or request.session.tipousuario_id == 5 %} <!-- Tipo de Usuarios Taller y Gerencia-->
                <a href="{% url 'pedidoestado' pedido.id 4 %}" class="btn btn-success">Cambiar Estado a Finalizado</a>
            {% endif %}
        </div>

        {% if items %}

            <h2>Items</h2>
    
            <table class="table table-sm table-striped table-borderless">
                <thead class="table-dark">
                    <tr>
                        <th>Cantidad</th>
                        <th>Producto</th>
                        {% if request.session.tipousuario_id != 4 %} <!-- Tipo de Usuarios Taller no visualizan los precios -->
                            <th>Precio Unitario</th>
                            <th>Subtotal</th>
                        {% endif %}
                        <th>Distancia Focal</th>
                        <th>Armazon</th>
                        <th>Lado</th>
                        {% if request.session.tipousuario_id != 4 %} <!-- Tipo de Usuarios Taller no puede eliminar items del pedido -->
                            <th></th>
                        {% endif %}
                    </tr>
                </thead>
            
                <tbody>
                    {% for item in items %}
                        <tr>
                            <td>{{ item.cantidad }}</td>
                            <td>{{ item.producto.nombre }}</td>
                            {% if request.session.tipousuario_id != 4 %} <!-- Tipo de Usuarios Taller no visualizan los precios -->
                                <td>{{ item.producto.precio }}$</td>
                                <td>{% widthratio item.producto.precio 1 item.cantidad %}$</td>
                            {% endif %}
                            <td>{{ item.distancia }}</td>
                            <td>{{ item.armazon }}</td>
                            <td>{{ item.lado }}</td>
                            {% if request.session.tipousuario_id != 4 %} <!-- Tipo de Usuarios Taller no puede eliminar items del pedido -->
                                <td style="width: 10%;">
                                    <a href="{% url 'itemdelete' item.id %}" class="btn btn-danger btn-sm botones-index">Eliminar</a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

        {% endif %}
        
        {% if request.session.tipousuario_id == 3 or request.session.tipousuario_id == 5 %} <!-- Tipo de Usuarios Ventas y Gerencia-->
            <div class="formulario">
                <h2>Cargar Item:</h2>
                <form action="{% url 'pedidoshow' pedido.id %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <div class="form-group" style="margin-top: 1rem;">
                        <input type="submit", class="btn btn-primary">
                    </div>
                </form>
            </div>
        {% endif %}

    </div>

    {% if request.session.tipousuario_id == 3 or request.session.tipousuario_id == 5 %} <!-- Tipo de Usuarios Ventas y Gerencia-->
        <script>
            // Esperamos a que se cargue el DOM
            document.addEventListener('DOMContentLoaded', function() {

                // Ocultamos los labels de las listas deplegables correspondientes a la clase lentes 
                $('label[for="id_lado"]').hide ();
                $('label[for="id_distancia"]').hide ();
                $('label[for="id_armazon"]').hide ();
        
                let producto = document.getElementById('id_producto');
                producto.addEventListener('change', (event) => {

                    // Tomamos el Id del Producto de la lista desplegable y hademos una consulta get para obtener el id de la categoria de ese producto
                    $.ajax({
                        type: "GET",
                        url: "{% url 'consulta' %}",
                        data: {
                            "check_this": producto.value,
                        },
                        success: function(data){
                            console.log("Consulta Exitosa");
                            console.log("Categoría Id:" + data.result);
                            if ( data.result == 1 ){
                                // Mostramos la lista desplegable del lado
                                document.getElementById('id_lado').style.display = 'block';
                                $('label[for="id_lado"]').show ();
                                // Mostramos la lista desplegable de la distancia
                                document.getElementById('id_distancia').style.display = 'block';
                                $('label[for="id_distancia"]').show ();
                                // Mostramos la lista desplegable del armazon
                                document.getElementById('id_armazon').style.display = 'block';
                                $('label[for="id_armazon"]').show ();
                            }else{
                                // Ocultamos la lista desplegable del lado
                                document.getElementById('id_lado').style.display = 'none'; 
                                $('label[for="id_lado"]').hide ();
                                // Ocultamos la lista desplegable de la distancia
                                document.getElementById('id_distancia').style.display = 'none'; 
                                $('label[for="id_distancia"]').hide ();
                                // Ocultamos la lista desplegable del armazon
                                document.getElementById('id_armazon').style.display = 'none'; 
                                $('label[for="id_armazon"]').hide ();
                            }
                        },
                        failure: function(data){
                            console.log("Hubo un error en la obtención del id de la categoría");
                        },
                    });
                });
            });
        </script>
    {% endif %}

{% endblock %}

clinica/templates/pedidos/update.html
{% extends "layout.html" %}
{% block body %}
    <div class="container">
        <div class="formulario">
            <h1>Modificar Pedido:</h1>
            <form action="{% url 'pedidosupdate' id %}" method="post">
                {% csrf_token %}
                {{ form }}
                <div class="form-group" style="margin-top: 1rem;">
                    <input type="submit", class="btn btn-primary">
                    <a href="{% url 'pedidoshow' id %}" class="btn btn-secondary">Volver</a>
                </div>
            </form>    
        </div>
    </div>
{% endblock %}